//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParandCartonUpdate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartonTechnicalInfo
    {
        public int Id { get; set; }
        public int OrderInfoId { get; set; }
        public Nullable<bool> type { get; set; }
        public string CartonType { get; set; }
        public Nullable<int> CartonCount { get; set; }
        public Nullable<int> CartonLength { get; set; }
        public Nullable<int> CartonWidth { get; set; }
        public Nullable<int> CartonHeight { get; set; }
        public Nullable<int> CartonWeight { get; set; }
        public Nullable<bool> IsCold { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public Nullable<bool> CartonEmpty { get; set; }
        public Nullable<int> ConnectorType { get; set; }
        public int Whosave { get; set; }
        public string CartonInsideType { get; set; }
        public Nullable<int> SheatCount { get; set; }
        public Nullable<int> SheatLength { get; set; }
        public Nullable<int> SheatWidth { get; set; }
        public string SheatType { get; set; }
        public Nullable<int> SheatWeight { get; set; }
    
        public virtual OrderInfo OrderInfo { get; set; }
    }
}
