//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParandCartonUpdate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParandCartondbEntities : DbContext
    {
        public ParandCartondbEntities()
            : base("name=ParandCartondbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CartonTechnicalInfo> CartonTechnicalInfoes { get; set; }
        public virtual DbSet<InsideProduct> InsideProducts { get; set; }
        public virtual DbSet<OrderInfo> OrderInfoes { get; set; }
        public virtual DbSet<PriceInfo> PriceInfoes { get; set; }
        public virtual DbSet<PrintInfo> PrintInfoes { get; set; }
        public virtual DbSet<ProductInfo> ProductInfoes { get; set; }
        public virtual DbSet<StandardInfo> StandardInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Layer> Layers { get; set; }
        public virtual DbSet<CartonType> CartonTypes { get; set; }
        public virtual DbSet<KelisheForm> KelisheForms { get; set; }
        public virtual DbSet<LogesticInfo> LogesticInfoes { get; set; }
        public virtual DbSet<ResultView> ResultViews { get; set; }
    }
}
