//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParandCartonUpdate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderInfo()
        {
            this.CartonTechnicalInfoes = new HashSet<CartonTechnicalInfo>();
            this.PrintInfoes = new HashSet<PrintInfo>();
            this.LogesticInfoes = new HashSet<LogesticInfo>();
        }
    
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public string CreateDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string SaleExpertCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string SaleExpertName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> NationalCode { get; set; }
        public Nullable<decimal> PostalCode { get; set; }
        public string EnterPriceInterfaceName { get; set; }
        public Nullable<decimal> EnconomicCode { get; set; }
        public Nullable<decimal> Tell { get; set; }
        public Nullable<decimal> EnterPriceInterfaceTell { get; set; }
        public string Email { get; set; }
        public int Whosave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartonTechnicalInfo> CartonTechnicalInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintInfo> PrintInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogesticInfo> LogesticInfoes { get; set; }
    }
}
