//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParandCartonUpdate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintInfo
    {
        public int Id { get; set; }
        public int OrderInfoId { get; set; }
        public int CartonTechnicalId { get; set; }
        public string PrintType { get; set; }
        public string ColorCount { get; set; }
        public string PrintTypeSelection { get; set; }
        public string PrintAmount { get; set; }
        public Nullable<bool> IsKelishe { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public string kelisheNum { get; set; }
        public string TemplateNum { get; set; }
        public int Whosave { get; set; }
        public string ColorCode1 { get; set; }
        public string ColorCode2 { get; set; }
        public string ColorCode3 { get; set; }
        public string ColorCode4 { get; set; }
        public string ColorCode5 { get; set; }
    
        public virtual OrderInfo OrderInfo { get; set; }
        public virtual PrintInfo PrintInfo1 { get; set; }
        public virtual PrintInfo PrintInfo2 { get; set; }
    }
}
