//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParandCartonUpdate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int Id { get; set; }
        public int LogesticInfoId { get; set; }
        public Nullable<double> TheAmountOfSheetsUsedForEachCarton { get; set; }
        public Nullable<double> MinimumBCT { get; set; }
        public Nullable<double> WasteRate { get; set; }
        public string DeliverTime { get; set; }
        public Nullable<bool> LayerCount { get; set; }
        public Nullable<int> Layer1 { get; set; }
        public Nullable<int> Layer2 { get; set; }
        public string FloatType1 { get; set; }
        public Nullable<int> Layer3 { get; set; }
        public Nullable<int> Layer4 { get; set; }
        public string FloatType2 { get; set; }
        public Nullable<int> Layer5 { get; set; }
        public Nullable<double> BCT { get; set; }
        public Nullable<double> ECT { get; set; }
        public int Whosave { get; set; }
    }
}
