//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParandCartonUpdate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultView
    {
        public string OrderCode { get; set; }
        public string CreateDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string SaleExpertCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string SaleExpertName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> NationalCode { get; set; }
        public Nullable<decimal> PostalCode { get; set; }
        public string EnterPriceInterfaceName { get; set; }
        public Nullable<decimal> EnconomicCode { get; set; }
        public Nullable<decimal> Tell { get; set; }
        public Nullable<decimal> EnterPriceInterfaceTell { get; set; }
        public string Email { get; set; }
        public int Whosave { get; set; }
        public Nullable<bool> type { get; set; }
        public string CartonType { get; set; }
        public Nullable<int> CartonCount { get; set; }
        public Nullable<int> CartonLength { get; set; }
        public Nullable<int> CartonWidth { get; set; }
        public Nullable<int> CartonHeight { get; set; }
        public Nullable<int> CartonWeight { get; set; }
        public Nullable<bool> IsCold { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public Nullable<bool> CartonEmpty { get; set; }
        public Nullable<int> ConnectorType { get; set; }
        public string CartonInsideType { get; set; }
        public Nullable<int> SheatCount { get; set; }
        public Nullable<int> SheatLength { get; set; }
        public Nullable<int> SheatWidth { get; set; }
        public string SheatType { get; set; }
        public string PrintType { get; set; }
        public int CartonTechnicalId { get; set; }
        public string ColorCount { get; set; }
        public string PrintTypeSelection { get; set; }
        public string PrintAmount { get; set; }
        public Nullable<bool> IsKelishe { get; set; }
        public Nullable<bool> PrintIsTemplate { get; set; }
        public string kelisheNum { get; set; }
        public string TemplateNum { get; set; }
        public Nullable<bool> LayoutType { get; set; }
        public Nullable<int> LayoutCount { get; set; }
        public Nullable<bool> TypeOfUse { get; set; }
        public Nullable<int> ProductDistance { get; set; }
        public Nullable<bool> DeliveryMethod { get; set; }
        public Nullable<int> AnbareshTime { get; set; }
        public string SendMethod { get; set; }
        public string LogesticTypeSelection { get; set; }
        public string Humidity { get; set; }
        public Nullable<bool> UseAddress { get; set; }
        public string OtherAddress { get; set; }
        public Nullable<double> TheAmountOfSheetsUsedForEachCarton { get; set; }
        public Nullable<double> MinimumBCT { get; set; }
        public Nullable<double> WasteRate { get; set; }
        public string DeliverTime { get; set; }
        public Nullable<bool> LayerCount { get; set; }
        public Nullable<int> Layer1 { get; set; }
        public Nullable<int> Layer2 { get; set; }
        public string FloatType1 { get; set; }
        public Nullable<int> Layer3 { get; set; }
        public Nullable<int> Layer4 { get; set; }
        public string FloatType2 { get; set; }
        public Nullable<double> BCT { get; set; }
        public Nullable<int> Layer5 { get; set; }
        public Nullable<double> ECT { get; set; }
        public Nullable<double> costpervaragh { get; set; }
        public Nullable<double> costofall { get; set; }
        public Nullable<double> malyat { get; set; }
        public Nullable<double> takhfif { get; set; }
        public Nullable<double> sumofall { get; set; }
        public int ProductInfoId { get; set; }
        public string Description { get; set; }
        public string ColorCode5 { get; set; }
        public string ColorCode4 { get; set; }
        public string ColorCode3 { get; set; }
        public string ColorCode2 { get; set; }
        public string ColorCode1 { get; set; }
        public Nullable<decimal> Countofkafchin { get; set; }
        public Nullable<decimal> CountinRise { get; set; }
        public Nullable<decimal> CountinBox { get; set; }
        public Nullable<decimal> CountofPalet { get; set; }
    }
}
